name: Build and deploy Python app to Azure Web App - crud-cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Esto es requerido para actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        working-directory: backend
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        working-directory: backend  # 🔥 Todas las operaciones se hacen dentro de "backend"
        run: pip install -r requirements.txt
      
      # Optional: Agregar paso para correr tests (PyTest, Unittest, etc.)
      #- name: Run tests
      #  working-directory: backend
      #  run: pytest

      - name: Zip artifact for deployment
        working-directory: backend
        run: zip -r ../release.zip ./ -x "venv/*"  # 🔥 Excluye venv/

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Esto es requerido para solicitar el JWT
      contents: read # Esto es requerido para actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_672D638AE56D4605A8911774C3F102F0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_727CE8763E8D4987829B044DD120EDCD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0FAA88118D59433C9DC09D6777C9C598 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'crud-cloud'
          slot-name: 'Production'
